---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "quay.io/rockylinux/rockylinux:8.7.20230215"
    pre_build_image: true
  - name: instance
    image: "quay.io/rockylinux/rockylinux:9.1.20230215-ubi"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
