---
role_name_check: 1
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubi8:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible