---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - include_vars: main.yml

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check whether a package called python is installed
      ansible.builtin.debug:
        msg: "python version installed: {{ ansible_facts.packages['python39'][0]['version'] }}"
      when: "'python39' in ansible_facts.packages"

    - name: Check whether a package called git is installed
      ansible.builtin.debug:
        msg: "git version installed: {{ ansible_facts.packages['git'][0]['version'] }}"
      when: "'git' in ansible_facts.packages"

    - name: Check /etc/pip.conf
      ansible.builtin.stat:
        path: "/etc/pip.conf"
      register: pip_file

    - name: Check if /etc/pip.conf file exists
      ansible.builtin.assert:
        that:
          - pip_file.stat.exists == True
        success_msg: "/etc/pip.conf file exists"
        fail_msg: "/etc/pip.conf file doesn't exist"

    - name: Check /etc/ansible/ansible.cfg
      ansible.builtin.stat:
        path: "/etc/ansible/ansible.cfg"
      register: ansible_cfg_file

    - name: Check if /etc/ansible/ansible.cfg file exists
      ansible.builtin.assert:
        that:
          - ansible_cfg_file.stat.exists == True
        success_msg: "/etc/ansible/ansible.cfg file exists"
        fail_msg: "/etc/ansible/ansible.cfg file doesn't exist"

    - name: Check venv dir
      ansible.builtin.stat:
        path: "/app/venv/venv_ansible_{{ ansible_release_version }}"
      register: venv_dir

    - name: Check if venv dir exists
      ansible.builtin.assert:
        that:
          - venv_dir.stat.exists == True
        success_msg: "/app/venv/venv_ansible_{{ ansible_release_version }} dir exists"
        fail_msg: "/app/venv/venv_ansible_{{ ansible_release_version }} dir doesn't exist"
