---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  vars:
    ansible_release_version: '6.5.0'

  tasks:
  - name: Example assertion
    ansible.builtin.assert:
      that: true

  - name: Gather the package facts
    ansible.builtin.package_facts:
      manager: auto

  - name: Check whether a package called python is installed
    ansible.builtin.debug:
      msg: "python version installed: {{ ansible_facts.packages['python39'][0]['version'] }}"
    when: "'python39' in ansible_facts.packages"

  - name: Check whether a package called git is installed
    ansible.builtin.debug:
      msg: "git version installed: {{ ansible_facts.packages['git'][0]['version'] }}"
    when: "'git' in ansible_facts.packages"

  - name: Check venv dir
    ansible.builtin.stat:
      path: "/app/venv/venv_ansible_{{ ansible_release_version }}"
    register: venv_dir

  - name: Check if venv dir exists
    ansible.builtin.assert:
      that:
        - venv_dir.stat.exists == True
      success_msg: "/app/venv/venv_ansible_{{ ansible_release_version }} dir exists"
      fail_msg: "/app/venv/venv_ansible_{{ ansible_release_version }} dir doesn't exist"
