---
name: Molecule Test
on: [push, pull_request]

defaults:
  run:
    working-directory: 'test.ansible-venv-setup'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.x"]

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'test.ansible-venv-setup'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install yamllint dependencies
        run: pip3 install yamllint

      - name: Check code syntax with yamllint
        run: |
          yamllint .

      - name: Install other dependencies
        run: |
          python3 --version
          pip3 install ansible molecule molecule[podman] podman
          ansible --version
          molecule --version
          pwd
          ls -la

      - name: Check code syntax with yamllint
        run: |
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
