---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.x"]

    steps:
      - uses: actions/checkout@v2
        with:
          path: molecule_demo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 --version
          pytnon3.11 -m venv venv 
          source venv/bin/activate
          pip3 install ansible molecule molecule[docker] docker
          ansible --version
          molecule --version
      - name: Lint with molecule
        run: |
          molecule --debug lint