---
name: Molecule Test
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.x"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Check code syntax with yamllint
        run: |
          yamllint .

      - name: Install dependencies
        run: |
          python3 --version
          pip3 install ansible molecule molecule[podman] podman
          ansible --version
          molecule --version

      - name: Check code syntax with yamllint
        run: |
          molecule lint
